### ISSUE TITLE
PSP34 optional extension for enumerable collections

### ISSUE THREAD

**Issue by 0xYogiBear** [w3f/PSPs#47]
Most of NFT collections are enumerable. I think functions relevant for enumerable collections should be added to PSP34 as optional extension, like it done in ERC721Enumerable.

ERC721Enumerable standard includes the following functions:
```
totalSupply() external view returns (uint256);
tokenByIndex(uint256 _index) external view returns (uint256);
tokenOfOwnerByIndex(address _owner, uint256 _index) external view returns (uint256);
```

**Comment by xgreenx** [comment]
I agree with you, it is why we implemented that extension in [OpenBrush](https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/src/traits/psp34/extensions/enumerable.rs#L31).

We didn't add it to the PSP because I'm not sure we can add optional extensions after the finalization of the PSP.

I can create a PR with it, and after we see is it okay or not=)

**Comment by 0xYogiBear** [comment]
It's great you implementing this extension in OpenBrush. It will be way better if the extension will be part of standard, since not all NFT project will use OpenBrush.
Hope the PR will be accepted. It's not change existing functions, just add new optional functions.
